brand:
  name: Jocelyn Yoga Test
menu-string: Menu

nav:
  - title: About
    url: '#about'
  - title: Sessions
    url: '#sessions'
  - title: About
    url: '#about'
  - title: Schedule
    url: '#schedule'
  - title: Connect
    url: '#connect'

copyright: Copyright &copy; Jocelyn Yoga 2019

social-buttons:
  - icon: fa fa-instagram
    url: 'https://www.instagram.com/joce.yoga/?hl=en'
  - icon: fa fa-facebook
    url: 'https://www.facebook.com/jocelynyoga/'

quicklinks:
  - title: Privacy Policy
    url: '#'
  - title: Terms of Use
    url: '#'

modal:
  date-string: 'Date: '
  client-string: 'Client: '
  category-string: 'Category: '
  close-icon: 'fa fa-times'
  close-string: 'Close Project'
